branch-defaults:
  default:
    environment: Osomaherapp-env
deploy:
  artifact: www/Archive.zip
environment-defaults:
  Osoapp-env-1:
    branch: null
    repository: null
  Osomaherapp-env:
    branch: null
    repository: null
global:
  application_name: osomaher-app
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
